### ISSUE TITLE
Can't add my mapping tool in execution framework

### ISSUE THREAD

**Issue by alloka** [kg-construct/KROWN#9]
Hello,

I'm getting the following error when I try to add my tool to be supported by KROWN: 

`Unknown resource "souffle"
No cases discovered!`

kindly find my files in an attached zip file
[files.zip](https://github.com/user-attachments/files/16996858/files.zip)

thanks in advance.
Ali.

**Comment by DylanVanAssche** [comment]
You closed this issue, I think you found the problem already?

If you run the tool with `--verbose`, it will tell you much more where things go wrong.
